include: package:flutter_lints/flutter.yaml

linter:

  rules:

analyzer:
  errors:
     invalid_annotation_target: ignore
  exclude:
    - lib/**/__generated__/**.dart
    - lib/**/**.freezed.dart
    - lib/**/**.g.dart
   
